build-asic example *args:
    cargo build -Fasic --example {{example}} {{args}}

run-asic example *args:
    cargo \
        --config "target.riscv64imac-unknown-none-elf.runner = 'riscv32-unknown-elf-gdb -x connect-and-load.gdb'" \
        run -Fasic --example {{example}} {{args}}

clippy-asic *args:
    cargo clippy -Fasic --examples -- -Dclippy::style

alias asic := run-asic
