MEMORY
{
  BOOTRAM : ORIGIN = 0x10000, LENGTH = 0x8000
  SDRAM : ORIGIN = 0x100000000, LENGTH = 0x70000000
}

REGION_ALIAS("REGION_TEXT", BOOTRAM);
REGION_ALIAS("REGION_RODATA", BOOTRAM);
REGION_ALIAS("REGION_DATA", BOOTRAM);
REGION_ALIAS("REGION_BSS", BOOTRAM);
REGION_ALIAS("REGION_HEAP", SDRAM);
REGION_ALIAS("REGION_STACK", BOOTRAM);
