MEMORY
{
  BOOTRAM : ORIGIN = 0x10000, LENGTH = 0x8000
  SDRAM : ORIGIN = 0x110000000, LENGTH = 0x60000000
}

REGION_ALIAS("REGION_TEXT", BOOTRAM);
REGION_ALIAS("REGION_RODATA", SDRAM);
REGION_ALIAS("REGION_DATA", SDRAM);
REGION_ALIAS("REGION_BSS", SDRAM);
REGION_ALIAS("REGION_HEAP", SDRAM);
REGION_ALIAS("REGION_STACK", SDRAM);
