MEMORY
{
  BOOTRAM : ORIGIN = 0x10000, LENGTH = 0x8000
  SDRAM : ORIGIN = 0x104080000, LENGTH = 0x1bf80000
}

REGION_ALIAS("REGION_TEXT", SDRAM);
REGION_ALIAS("REGION_RODATA", SDRAM);
REGION_ALIAS("REGION_DATA", SDRAM);
REGION_ALIAS("REGION_BSS", SDRAM);
REGION_ALIAS("REGION_HEAP", SDRAM);
REGION_ALIAS("REGION_STACK", SDRAM);
