build-sysctrl:
    cargo build --target=riscv32imc-unknown-none-elf -Fpanic-uart
    ./weaken_compiler_builtins.sh

build-hpc:
    cargo build --target=riscv64imac-unknown-none-elf -Fpanic-uart
    ./weaken_compiler_builtins.sh
